# main keyboards
HELP_KEY: str = "Help ❔"
LOGIN_KEY: str = "Login To Instagram 🔐"
PRIVACY_KEY: str = "Privacy 🔒"
LOTTERY_KEY: str = "Lottery 🎲"
BACK_KEY: str = "Back ◀️"

#user wallets keys
USER_WALLET_KEY: str = "Wallet and Twitter 💰"
SHOW_ADDRESS_KEY: str = "View Address 💲"
SHOW_TWITTER_USER_KEY: str = "View Twitter username👨‍💼"
ADD_ADDRESS_KEY: str = "BSC Address 💲"
ADD_TWITTER_USER_KEY: str = "Twitter usersname 👨‍💼"
CHANGE_ADDRESS_KEY: str = "Change Address 💲"
CHANGE_TWITTER_USER_KEY: str = "Change Twitter username 👨‍💼"

# admin panel keys
ADMIN_KEY: str = "Admin 👨‍💼"
BACK_TO_HOME_KEY: str = "Back To Home 🏚️"
TWITTER_KEY: str = "Twitter 💬"
SEARCH_KEY: str = "Search 🔎"
PROCEED_KEY: str = "Proceed"
DATE_KEY: str = "Date 📅"
GET_TWEETS_KEY: str = "Get tweets"
SEND_TWEETS_KEY: str = "Send 💬"
STOP_GET_TWEETS_KEY: str = "Stop Getting Tweets ✋"
STOP_SEND_TWEETS_KEY: str = "Stop Sending Tweets ✋"
UPLOAD_PHOTO_KEY: str = "Upload Photo 📤"
STOP_SENDIND_TWEETS_KEY: str = "Stop ✋"
COMPETITION_KEY: str = "Comp 🏆"
SETUP_POINTS_KEY: str = "Setup Points"
SET_POINTS_KEY: str = "Set Points"
CHANGE_POINTS_KEY: str = "Change Points 📝"
START_COMPETITION_KEY: str = "Start"
STOP_COMPETITION_KEY: str = "Stop ✋"
LEADERBOARD_KEY: str = "Leaderboard 📊"
SET_TIME_LEADERBOARD_KEY: str = "Time Interval ⏱"
DISPLAY_BOARD_KEY: str = "Display"
HIDE_BOARD_KEY: str = "Hide"
SECS_KEY: str = "Sec(s)"
MINS_KEY: str = "Min(s)"
HOURS_KEY: str = "Hour(s)"
DAYS_KEY: str = "Day(s)"
PARTICIPANT_KEY: str = "Participant 👨‍💼"
VIEW_PARTICIPANT_KEY: str = "View Participant"
BAN_PARTICIPANT_KEY: str = "Ban Participant"
DISTRIBUTE_TOKEN_KEY: str = "Send Token To winners"
SET_PRIZE_KEY: str = "Set Prize"
CHANGE_PRIZE_KEY: str = "Change Prize 📝"
SEND_TOKEN_KEY: str = "Send Token"
ADMIN_WALLET_KEY: str = "Wallet 💰"
ADMIN_CREAT_WALLET_KEY: str = "Create Wallet 💰"
VIEW_WALLET_KEY: str = "Wallet Details 📝"
DELETE_WALLET_KEY: str = "Delete Wallet 🚮"
SEND_MESSAGE_KEY: str = "Send Message"

# feedback key
FEEDBACK_KEY: str = "Feedback 💡"
