(  # states
    # start
    START_STATE,
    # home
    HOME_STATE,
    HELP_STATE,
    LOGIN_STATE,
    ADMIN_STATE,
    FEEDBACK_STATE,

    #user wallet and twitter
    USER_WALLET_STATE,
    ADD_USER_WALLET_STATE,
    VIEW_USER_WALLET_STATE,
    CHANGE_USER_WALLET_STATE,
    STORE_ADDRESS_STATE,
    STORE_USERNAME_STATE,
    STORE_PASS_STATE,
    VIEW_ADDRESS_STATE,
    VIEW_PASS_STATE,
    VIEW_USERNAME_STATE,
    CHANGE_PASS_STATE,
    CHANGE_ADDRESS_STATE,
    CHANGE_USERNAME_STATE,

    # login
    SET_POST_LINK_AND_GET_TYPE_OF_LOTTERY,
    IS_YOUR_LOGIN_INFORMATION_SAVED_FOR_THE_NEXT_LOGIN,
    LOGIN_WITH_TWO_FACTOR_AUTHENTICATION,
    # lottery
    LOTTERY,
    # upload
    IS_YOUR_LOGIN_INFORMATION_SAVED_FOR_THE_NEXT_LOGIN_IN_UPLOAD,
    LOGIN_WITH_TWO_FACTOR_AUTHENTICATION_FOR_UPLOAD,
    LOGIN_ATTEMPT_AND_GET_MEDIA_TYPE,
    SET_MEDIA_TYPE_AND_GET_MEDIA,
    SET_MEDIA_AND_GET_CAPTION,
    SET_CAPTION_AND_ASKING_TO_CONFIRM_THE_CONTENT,
    SET_TITLE_OF_IGTV_AND_GET_CAPTION,
    VERIFY_CONTENT_AND_UPLOAD_ON_INSTAGRAM,
    # admin
    TWITTER_STATE,
    SEARCH_STATE,
    SEARCH_DATE_STATE,
    COMPETITION_STATE,
    ADMIN_WALLET_STATE,
    SEND_MESSAGE_TO_ALL_USER,
) = range(37)
