(  # states
    # start
    START_STATE,
    # home
    HOME_STATE,
    HELP_STATE,
    LOGIN_STATE,
    ADMIN_STATE,
    FEEDBACK_STATE,

    #user wallet and twitter
    USER_WALLET_STATE,
    ADD_USER_WALLET_STATE,
    VIEW_USER_WALLET_STATE,
    CHANGE_USER_WALLET_STATE,
    STORE_ADDRESS_STATE,
    STORE_USERNAME_STATE,
    VIEW_ADDRESS_STATE,
    VIEW_USERNAME_STATE,
    CHANGE_ADDRESS_STATE,
    CHANGE_USERNAME_STATE,
    OPT_CHANGE_ADDRESS_STATE,
    OPT_CHANGE_USERNAME_STATE,
    VIEW_USERNAME_ADD_ADDR_STATE,
    ADD_USERNAME_VIEW_ADDR_STATE,

    # admin
    TWITTER_STATE,
    SEARCH_STATE,
    SEARCH_DATE_STATE,
    COMPETITION_STATE,
    ADMIN_WALLET_STATE,
    SEND_MESSAGE_TO_ALL_USER,
) = range(26)
